spring:
  application:
    name: eureka
eureka:
  client:
    service-url:
      deaultZone: http://localhost:8761/eureka/
    server:
      enable-self-preservation: false
    register-with-eureka: true
server:
  port: 8761